### ISSUE TITLE
Export/Verification Question

### ISSUE THREAD

**Issue by Mikahael** [FireHead90544/PyMailer#1]
Hey sir, I was wondering, if I use this app through google server or mail, it will ask me for authentication. How to avoid that sir?

**Comment by FireHead90544** [comment]
Hello There Mikhael,
I hope you are doin well.
As you mentioned, while using gmail's smtp settings, it will require you authentication. To bypass that you simply have two (or maybe more) options, 
1. Enable [LesSecureApps](https://myaccount.google.com/lesssecureapps) and turn on [DisplayUnlockCaptcha](https://accounts.google.com/b/0/DisplayUnlockCaptcha) for the moment you are trying to log in using the application. Though sometimes, it doesn't work and neither it is advised to use this method.

2. This method is recommended and is much better. Just create an [App Password](https://myaccount.google.com/apppasswords) for your application, and use that password to sign in to the application, it won't ask you for any more authentication that way.

I hope this clears your doubt, and helps you solve your problem.

Thanks,
Rudransh :)
